### ISSUE TITLE
Error in currently selected datapack with TEN3

### ISSUE THREAD

**Issue by Thepigcat76** [cm6744/TechnicalEngineering3-1.16.5#1]
I cant enter a world because it says Datapck Loading Error and i think TEN3 is responsible here is the latest.log
[latest.log](https://github.com/cm6744/TechnicalEngineering3-1.16.5/files/9460982/latest.log)
I am using Minecraft 1.18.2 - Forge: 40.1.74 Mod: TEN3-18.10

**Comment by furtabs** [comment]
Seems to be incompatibility with KubeJS also i can duplicate this

**Comment by cm6744** [comment]
That's true. I read a log months ago, but I can't find any bugs.And it still goes wrong. Avoid using kubejs maybe the only choice.Or wait someone to point my mistake.

**Comment by cm6744** [comment]
If you can, present a crash log please.I will try again.
