### ISSUE TITLE
[非重要]多人游戏服务器无法进入且提示:io.netty.handler.codec.EncoderException: java.lang.NullPointerException.

### ISSUE THREAD

**Issue by NitrogenMilk** [cm6744/TechnicalEngineering3-1.16.5#2]
*此bug似乎并非常见如果您有时间的话再尝试修复*❤ヾ(≧▽≦*)o

环境：
Java版本：Jre8-u261
服务端版本：1.16.5Forge36.2.34.
客户端版本：1.16.5Forge36.2.34, ViveCraft-8b,修改Optifine1.16.5_HD_U_G8_LIB.
服务端完整mod列表：
![image](https://github.com/cm6744/TechnicalEngineering3-1.16.5/assets/106051667/1f7f27c5-323d-4569-8960-9762eeca6319)
客户端完整mod列表：
![image](https://github.com/cm6744/TechnicalEngineering3-1.16.5/assets/106051667/3938e010-789c-4b3f-b89d-e6848e60c114)

遇到的问题：
无法进行多人游戏，在加载世界时客户端内部错误断开连接并提示io.netty.handler.codec.EncoderException: java.lang.NullPointerException.
且服务端与客户端**似乎**未输出除了断开连接之外的任何相关信息。

服务端日志：
[2023-07-20-11.log](https://github.com/cm6744/TechnicalEngineering3-1.16.5/files/12099236/2023-07-20-11.log)
客户端日志：
[2023-07-20-12.log](https://github.com/cm6744/TechnicalEngineering3-1.16.5/files/12099240/2023-07-20-12.log)

这是我打算做vr多人游戏整合包时发现的问题，我并未尝试过无vr版本与删除其他模组的运行情况，因此这个问题可能并非十分严重。
同时因为这个客户端带有Optifine与部分修改内容所以如果您没有大量空余时间的话不建议花费大量精力来修复这个bug。
作者加油捏ヾ(≧▽≦*)o

_我能够在Issues中附带我的个人联系方式吗:Jisoadng@outlook.com_

**Comment by cm6744** [comment]
很抱歉最近没有关注github。
这个问题应该已经在最新版本修复了，的确是我的问题
